title: Xevion.dev
email: xevion@xevion.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xevion.dev" # the base hostname & protocol for your site, e.g. http://example.com
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-environment-variables
include:
  - _pages
  - CNAME
exclude:
  - LICENSE
sass:
  style: compressed
  sourcemap: development
# compress_html:
#   ignore:
#     envs: [development, production]
#   comments: all
#   clippings: all
#   endings: all
#   blanklines: false
repository: Xevion/xevion.dev
defaults:
  -
    scope:
      path: "_pages"
    values:
      permalink: "/:title:output_ext"