title: Xevion.dev
environment: production
email: xevion@xevion.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xevion.dev" # the base hostname & protocol for your site, e.g. http://example.com
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - "jekyll-github-metadata"
  - jekyll-redirect-from
exclude:
    - CNAME
    - LICENSE
sass:
  style: compressed
compress_html:
  ignore:
    envs: ["development"]
  comments: all
repository: Xevion/xevion.dev