title: Xevion.dev
email: xevion@xevion.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xevion.dev" # the base hostname & protocol for your site, e.g. http://example.com
github: xevion
highlighter: rouge
plugins:
  - jekyll-feed
exclude:
    - CNAME
    - LICENSE
sass:
  style: compressed